// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQjiK1nKVO8mNdzICNLrjYLihqgOjr5e4',
    appId: '1:492824331275:web:7435a1b352e75c4ef2730e',
    messagingSenderId: '492824331275',
    projectId: 'steps-tracker-af8dc',
    authDomain: 'steps-tracker-af8dc.firebaseapp.com',
    storageBucket: 'steps-tracker-af8dc.firebasestorage.app',
    measurementId: 'G-ME53KSTBRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8gyUjJpzitjMf9d5HGwWepvbg53IM1ig',
    appId: '1:492824331275:android:33e040cafec4432df2730e',
    messagingSenderId: '492824331275',
    projectId: 'steps-tracker-af8dc',
    storageBucket: 'steps-tracker-af8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlC6AOWtXnlpJ01YBzONIk8nB3qAFsCn0',
    appId: '1:492824331275:ios:f1112428639a4495f2730e',
    messagingSenderId: '492824331275',
    projectId: 'steps-tracker-af8dc',
    storageBucket: 'steps-tracker-af8dc.firebasestorage.app',
    iosBundleId: 'com.example.stepsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlC6AOWtXnlpJ01YBzONIk8nB3qAFsCn0',
    appId: '1:492824331275:ios:f1112428639a4495f2730e',
    messagingSenderId: '492824331275',
    projectId: 'steps-tracker-af8dc',
    storageBucket: 'steps-tracker-af8dc.firebasestorage.app',
    iosBundleId: 'com.example.stepsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQjiK1nKVO8mNdzICNLrjYLihqgOjr5e4',
    appId: '1:492824331275:web:655bc979a35101c2f2730e',
    messagingSenderId: '492824331275',
    projectId: 'steps-tracker-af8dc',
    authDomain: 'steps-tracker-af8dc.firebaseapp.com',
    storageBucket: 'steps-tracker-af8dc.firebasestorage.app',
    measurementId: 'G-JTFJHJTF83',
  );
}
